name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    env:
      Test_Project_Path: SqlTableDependency.Extensions.Tests\SqlTableDependency.Extensions.Tests.csproj
      Joker_MVVM_Test_Project_Path: Joker.MVVM\Joker.MVVM.Tests.csproj
      Joker_Redis_Test_Project_Path: Joker.Redis.Tests\Joker.Redis.Tests.csproj

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    # Test
    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path
    - name: Execute Joker.MVVM Unit Tests
      run: dotnet test $env:Joker_MVVM_Test_Project_Path
    - name: Execute Joker.Redis Unit Tests
      run: dotnet test $env:Joker_Redis_Test_Project_Path
