name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    env:
      Test_Project_Path: Joker.MVVM\Joker.MVVM.csproj

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    # Test
    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path
